name: Base Image Create

on:
  workflow_dispatch:

concurrency:
  group: create-base-img
  cancel-in-progress: true

jobs:

  manylinux64:
    name: ManyLinux • ${{ matrix.build_arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        build_arch: [ "arm64", "amd64" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Base Image
        uses: actions/cache@v3
        id: base-manylinux
        with:
          path: /tmp/.cache-base
          key: ${{ matrix.build_arch }}-buildx-${{ hashFiles('docker/manylinux64.Dockerfile') }}

      - name: Create Cache Dir
        if: steps.base-manylinux.outputs.cache-hit != 'true'
        run: mkdir /tmp/.cache-base

      - name: Build Base Image
        if: steps.base-manylinux.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/${{ matrix.build_arch }}
          push: false
          tags: base-manylinux-${{ matrix.build_arch }}:latest
          file: docker/manylinux64.Dockerfile
          outputs: type=docker,dest=/tmp/.cache-base/base-manylinux-${{ matrix.build_arch }}.tar

      - name: Debug Step
        run: ls -la /tmp/.cache-base/

  manylinux:
    name: ManyLinux • armv7
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Base Image
        uses: actions/cache@v3
        id: base-manylinux
        with:
          path: /tmp/.cache-base
          key: armv7-buildx-${{ hashFiles('docker/manylinux.Dockerfile') }}

      - name: Create Cache Dir
        if: steps.base-manylinux.outputs.cache-hit != 'true'
        run: mkdir /tmp/.cache-base

      - name: Build Base Image
        if: steps.base-manylinux.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm/v7
          push: false
          tags: base-manylinux-armv7:latest
          file: docker/manylinux.Dockerfile
          outputs: type=docker,dest=/tmp/.cache-base/base-manylinux-armv7.tar

      - name: Debug Step
        run: ls -la /tmp/.cache-base/
