name: Build Base Image

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, edited]
    paths:
      - 'docker/base/*.Dockerfile'
  push:
    branches: [master]
    paths:
      - 'docker/base/*.Dockerfile'
  workflow_dispatch:

concurrency:
  group: build-base
  cancel-in-progress: true

jobs:

  manylinux:
    name: ManyLinux • ${{ matrix.build_arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_arch: [ "armv7", "arm64", "amd64" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ARM64 prepare
        if: matrix.build_arch == 'arm64'
        run: |
          echo BASE_DOCKER_FILE="docker/base/manylinux64.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm64" >> $GITHUB_ENV
          echo BUILD_IMG="quay.io/pypa/manylinux2014_aarch64" >> $GITHUB_ENV

      - name: AMD64 prepare
        if: matrix.build_arch == 'amd64'
        run: |
          echo BASE_DOCKER_FILE="docker/base/manylinux64.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/amd64" >> $GITHUB_ENV
          echo BUILD_IMG="quay.io/pypa/manylinux2014_x86_64" >> $GITHUB_ENV

      - name: ARMv7 prepare
        if: matrix.build_arch == 'armv7'
        run: |
          echo BASE_DOCKER_FILE="docker/base/manylinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm/v7" >> $GITHUB_ENV
          echo BUILD_IMG="debian:11" >> $GITHUB_ENV

      - name: Build Base Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.BASE_DOCKER_FILE }}
          build-args: BUILD_IMG=${{ env.BUILD_IMG }}
          platforms: ${{ env.BUILD_PLATFORM }}
          push: false
          cache-from: type=gha,mode=max,scope=build-manylinux-${{ matrix.build_arch }}
          cache-to: type=gha,mode=max,scope=build-manylinux-${{ matrix.build_arch }}
          tags: base-manylinux-${{ matrix.build_arch }}:latest
          target: base

  musllinux:
    name: MuslLinux • ${{ matrix.build_arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_arch: [ "armv7", "arm64", "amd64" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ARM64 prepare
        if: matrix.build_arch == 'arm64'
        run: |
          echo BASE_DOCKER_FILE="docker/base/musllinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm64" >> $GITHUB_ENV
          echo BUILD_IMG="alpine:3.15" >> $GITHUB_ENV

      - name: AMD64 prepare
        if: matrix.build_arch == 'amd64'
        run: |
          echo BASE_DOCKER_FILE="docker/base/musllinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/amd64" >> $GITHUB_ENV
          echo BUILD_IMG="alpine:3.15" >> $GITHUB_ENV

      - name: ARMv7 prepare
        if: matrix.build_arch == 'armv7'
        run: |
          echo BASE_DOCKER_FILE="docker/base/musllinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm/v7" >> $GITHUB_ENV
          echo BUILD_IMG="alpine:3.15" >> $GITHUB_ENV

      - name: Build Base Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.BASE_DOCKER_FILE }}
          build-args: BUILD_IMG=${{ env.BUILD_IMG }}
          platforms: ${{ env.BUILD_PLATFORM }}
          push: false
          cache-from: type=gha,mode=max,scope=build-musllinux-${{ matrix.build_arch }}
          cache-to: type=gha,mode=max,scope=build-musllinux-${{ matrix.build_arch }}
          tags: base-musllinux-${{ matrix.build_arch }}:latest
          target: base
