name: Build Framework Image

on:
  workflow_dispatch:

concurrency:
  group: build-framework
  cancel-in-progress: true

jobs:
  manylinux:
    name: ManyLinux • ${{ matrix.build_arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_arch: [ "arm64", "amd64" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ARM64 prepare
        if: matrix.build_arch == 'arm64'
        run: |
          echo BASE_DOCKER_FILE="docker/build/manylinux64.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm64" >> $GITHUB_ENV
          echo BUILD_IMG="quay.io/pypa/manylinux2014_aarch64" >> $GITHUB_ENV

      - name: AMD64 prepare
        if: matrix.build_arch == 'amd64'
        run: |
          echo BASE_DOCKER_FILE="docker/build/manylinux64.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/amd64" >> $GITHUB_ENV
          echo BUILD_IMG="quay.io/pypa/manylinux2014_x86_64" >> $GITHUB_ENV

      - name: ARMv7 prepare
        if: matrix.build_arch == 'armv7'
        run: |
          echo BASE_DOCKER_FILE="docker/build/manylinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm/v7" >> $GITHUB_ENV
          echo BUILD_IMG="debian:11" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Production Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.BASE_DOCKER_FILE }}
          build-args: BUILD_IMG=${{ env.BUILD_IMG }}
          platforms: ${{ env.BUILD_PLATFORM }}
          push: true
          cache-from: type=gha,mode=max,scope=build-manylinux-${{ matrix.build_arch }}
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY }}/manylinux_${{ matrix.build_arch }}:latest
          target: framework


#  musllinux:
#    name: MuslLinux • ${{ matrix.build_arch }}
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        build_arch: [ "arm64", "amd64" ]
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Setup Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: ARM64 prepare
#        if: matrix.build_arch == 'arm64'
#        run: |
#          echo BASE_DOCKER_FILE="docker/musllinux.Dockerfile" >> $GITHUB_ENV
#          echo BUILD_PLATFORM="linux/arm64" >> $GITHUB_ENV
#
#      - name: AMD64 prepare
#        if: matrix.build_arch == 'amd64'
#        run: |
#          echo BASE_DOCKER_FILE="docker/musllinux.Dockerfile" >> $GITHUB_ENV
#          echo BUILD_PLATFORM="linux/amd64" >> $GITHUB_ENV
#
#      - name: ARMv7 prepare
#        if: matrix.build_arch == 'armv7'
#        run: |
#          echo BASE_DOCKER_FILE="docker/musllinux.Dockerfile" >> $GITHUB_ENV
#          echo BUILD_PLATFORM="linux/arm/v7" >> $GITHUB_ENV
#
#      - name: Load Base Image Cache
#        uses: actions/cache@v3
#        id: base-musllinux
#        with:
#          path: /tmp/.cache-base
#          key: ${{ matrix.build_arch }}-base-${{ hashFiles( env.BASE_DOCKER_FILE ) }}
#
#      - name: Cache Production Image
#        uses: actions/cache@v3
#        id: production-musllinux
#        with:
#          path: /tmp/.cache-production
#          key: ${{ matrix.build_arch }}-prod-${{ hashFiles(env.BASE_DOCKER_FILE, 'requirements.txt') }}
#
#      - name: Load Base Image
#        if: steps.production-musllinux.outputs.cache-hit != 'true'
#        run: |
#          docker load --input /tmp/.cache-base/base-musllinux-${{ matrix.build_arch }}.tar
#          mkdir /tmp/.cache-production
#          docker ps
#
#      - name: Build Production Image
#        if: steps.production-musllinux.outputs.cache-hit != 'true'
#        run: |
#          docker run \
#              --platform ${{ env.BUILD_PLATFORM }} \
#              --name prod-musllinux-${{ matrix.build_arch }} \
#              -v $(realpath .):/build \
#              --workdir /build \
#              base-musllinux-${{ matrix.build_arch }}:latest \
#              python3 -m pip install -r ./requirements.txt
#          docker commit \
#              prod-musllinux-${{ matrix.build_arch }} prod-musllinux-${{ matrix.build_arch }}:latest
#          docker image save \
#              prod-musllinux-${{ matrix.build_arch }}:latest | gzip > \
#              /tmp/.cache-production/prod-musllinux-${{ matrix.build_arch }}.tar.gz
#
#      - name: Debug Step
#        run: |
#          ls -la /tmp/.cache-base/
#          ls -la /tmp/.cache-production/
