name: dev

on:
  workflow_dispatch:

env:
  APP_NAME: cloud_py_api

jobs:

  tests-mysql-socket:
    runs-on: ubuntu-22.04
    name: ${{ matrix.nextcloud }} • MySQL • socket
    if: "!contains(github.event.head_commit.message, '[docs]')"
    strategy:
      fail-fast: false
      matrix:
        nextcloud: [ "25.0.2" ]

    steps:
      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, fileinfo, intl, pdo_mysql, zip, gd

#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.9'
#
#      - name: cache-nextcloud
#        id: nextcloud_setup
#        uses: actions/cache@v3
#        with:
#          path: nextcloud-${{ matrix.nextcloud }}.tar.bz2
#          key: ${{ matrix.nextcloud }}
#
#      - name: Download Nextcloud
#        if: steps.nextcloud_setup.outputs.cache-hit != 'true'
#        run: wget -q https://download.nextcloud.com/server/releases/nextcloud-${{ matrix.nextcloud }}.tar.bz2

      - name: Set up Nextcloud
        run: |
          sudo ls -la /etc/mysql/conf.d/
          sudo ls -la /etc/mysql/mysql.conf.d/
          sudo cat /etc/mysql/mysql.conf.d/mysql.cnf
          echo "==="
          sudo cat /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo bash -c "echo '[client-server]' >> /etc/mysql/my.cnf"
          sudo bash -c "echo 'port = 3307' >> /etc/mysql/my.cnf"
          netstat -tulpn | grep LISTEN
          sudo systemctl restart mysql.service
          sudo cat /etc/mysql/my.cnf
          ls -la /var/run/mysqld/mysqld.sock
          netstat -tulpn | grep LISTEN

#          error
#          tar -xjf nextcloud-${{ matrix.nextcloud }}.tar.bz2 --strip-components 1
#          mkdir data
#          php occ maintenance:install --verbose --database=mysql --database-name=nextcloud \
#          --database-host=127.0.0.1 --database-user=root --database-pass=rootpassword \
#          --admin-user admin --admin-pass adminpassword
#          php occ config:system:set debug --value=true --type=boolean
#          php -S localhost:8080 &
